// actions/types.js

export const types = {
  LOAD_FONTS: 'LOAD_FONTS',
  FONTS_LOADED: 'FONTS_LOADED',
  TOGGLE_DRAWER: 'TOGGLE_DRAWER',
  GET_ARTICLES_LIST: 'GET_ARTICLES_LIST',
  FETCHING_ARTICLES_LIST: 'FETCHING_ARTICLES_LIST',
  RECEIVE_ARTICLES_LIST: 'RECEIVE_ARTICLES_LIST',
  GET_ARTICLE: 'GET_ARTICLE',
  GET_ARTICLE_BY_INDEX: 'GET_ARTICLE_BY_INDEX',
  FETCHING_ARTICLE: 'FETCHING_ARTICLE',
  RECEIVE_ARTICLE: 'RECEIVE_ARTICLE',
  FETCHING_LIST: 'FETCHING_LIST',
  FETCHING_ARTICLE: 'FETCHING_ARTICLE',
  FETCH_FAILED: 'FETCH_FAILED',
  NEXT_ARTICLE: 'NEXT_ARTICLE',
}
